import { create } from "zustand";
import type { FoldStateEvent, PredictSuggestion, ResolvedThought, ThoughtPhase } from "@fold/runtime";

interface OverlayStore extends FoldStateEvent {
	voiceLevel: number;
	setState: (partial: Partial<FoldStateEvent>) => void;
	setVoiceLevel: (level: number) => void;
	setLocalThought: (thought: ResolvedThought | null, phase: ThoughtPhase) => void;
	reset: () => void;
}

export const useOverlayStore = create<OverlayStore>((set) => ({
	status: "idle",
	transcript: "",
	thinkingText: undefined,
	progressMessage: undefined,
	steps: [],
	currentApp: null,
	result: null,
	resultDetail: null,
	error: null,
	askTitle: null,
	askMessage: null,
	askHint: null,
	askOptions: undefined,
	voiceMode: null,
	predictMode: null,
	predictPhase: null,
	predictSurface: null,
	predictAnchor: null,
	predictSuggestions: undefined,
	predictDrafts: undefined,
	predictSelectedIntent: null,
	predictDraftsLoading: false,
	predictCursor: null,
	contextAppName: null,
	contextAppPath: null,
	contextWindowTitle: null,
	contextPageUrl: null,
	contextPageLabel: null,
	predictRefining: false,
	voiceTabPlacement: null,
	thoughtPlacement: null,
	thoughtPhase: "hidden",
	thought: null,
	interimTranscript: "",
	structureDraftOpen: false,
	voiceLevel: 0,
	setState: (partial) => set((s) => ({ ...s, ...partial })),
	setVoiceLevel: (level) => set({ voiceLevel: level }),
	setLocalThought: (thought, thoughtPhase) => set({ thought, thoughtPhase }),
	reset: () =>
		set({
			status: "idle",
			transcript: "",
			thinkingText: undefined,
			progressMessage: undefined,
			steps: [],
			currentApp: null,
			result: null,
			resultDetail: null,
			error: null,
			askTitle: null,
			askMessage: null,
			askHint: null,
			askOptions: undefined,
			voiceMode: null,
			predictMode: null,
			predictPhase: null,
			predictSurface: null,
			predictAnchor: null,
			predictSuggestions: undefined,
			predictDrafts: undefined,
			predictSelectedIntent: null,
			predictDraftsLoading: false,
			predictCursor: null,
			contextAppName: null,
			contextAppPath: null,
			contextWindowTitle: null,
			contextPageUrl: null,
			contextPageLabel: null,
			predictRefining: false,
			voiceTabPlacement: null,
			thoughtPlacement: null,
			thoughtPhase: "hidden",
			thought: null,
			interimTranscript: "",
			structureDraftOpen: false,
			voiceLevel: 0,
		}),
}));

export type { PredictSuggestion };
