export { runShell, runAppleScript, runPython } from "./shell.js";
export {
	runSandboxedAppleScript,
	runSandboxedPython,
	runSandboxedShell,
	type SandboxedShellOptions,
} from "./sandbox.js";
export {
	createMailDraft,
	openMail,
	countMailUnread,
	openGogAuthInTerminal,
	openGwsAuthInTerminal,
	formatCliVendorMaintenanceHint,
	GMAIL_CLI_VENDORS,
	isGmailCliInstalled,
	resolveMailConnectorAsync,
	resolveMailConnector,
	detectMailConnector,
	connectorLabel,
	probeGmailCli,
	type GmailCliProbe,
	type MailDraftInput,
	type MailDraftResult,
	type MailDraftOptions,
	type MailActionOptions,
	type MailOpenResult,
	type MailCountUnreadResult,
	type MailContextHint,
	type MailProvider,
	type MailConnectorId,
} from "./mail/index.js";
export {
	browserEvaluate,
	connectBrowser,
	getChromeCdpUrl,
	getCurrentBrowserPage,
	listChromeTabsViaAppleScript,
	pickActiveChromeTab,
	probeBrowserCdp,
	withBrowserSession,
	CHAT_PLATFORMS,
	detectChatPlatforms,
	getChatPlatform,
	runChatProfileImport,
	type BrowserCdpProbe,
	type BrowserPageInfo,
	type BrowserSession,
	type ChromeTabInfo,
	type ChatPlatform,
	type ChatPlatformMatch,
	type ChatProfileImportResult,
} from "./browser/index.js";
export {
	browserInteract,
	type BrowserInteractAction,
	type BrowserInteractInput,
	type BrowserInteractResult,
} from "./browser/index.js";
export {
	executeAgent,
	isAgentSubagentsEnabled,
	listAvailableAgents,
	probeAllAgents,
	openCodexInstallInTerminal,
	openClaudeLoginInTerminal,
	type AgentId,
	type AgentProbeStatus,
	type AgentResult,
	type AgentResultEnvelope,
	type AgentTask,
	type AgentTaskEnvelope,
	type SubagentHandoff,
} from "./agents/index.js";
export {
	executeUitarsTask,
	isUitarsEnabled,
	probeUitars,
	type UitarsProbe,
	type UitarsTaskInput,
	type UitarsTaskResult,
} from "./gui/index.js";
export {
	discoverWorkBuddyGatewayUrl,
	discoverWorkBuddyMcpAuthHeader,
	discoverWorkBuddyMcpTokenFromProcess,
	executeWorkBuddyTask,
	getWorkBuddyGatewayUrl,
	isWorkBuddyEnabled,
	probeWorkBuddyGateway,
	resolveWorkBuddyMcpToken,
	type WorkBuddyProbe,
	type WorkBuddyRunInput,
	type WorkBuddyRunResult,
} from "./workbuddy/index.js";
export { workbuddyToolsFitIntent } from "./workbuddy/fit.js";
export { discoverWorkBuddyAppPath, isWorkBuddyAppInstalled, openWorkBuddyApp } from "./workbuddy/app.js";
export { discoverCodexAppPath, isCodexAppInstalled, openCodexApp } from "./agents/codex-app.js";
export {
	CodexAppServerClient,
	getSharedCodexAppServer,
	stopSharedCodexAppServer,
	resolveCodexBinary,
	type CodexRemoteClient,
	type CodexRemotePairing,
	type CodexRemoteStatus,
	type CodexRemoteStatusSnapshot,
} from "./agents/codex-app-server.js";
export { isCursorAppInstalled, openCursorAgentInstall, startCursorBrowserLogin } from "./agents/cursor-app.js";
export {
	beginWorkBuddyPairing,
	getWorkBuddyPairingPhrase,
	launchWorkBuddyPairScriptInTerminal,
	tryPersistWorkBuddyBridge,
} from "./workbuddy/bridge.js";
export {
	createNangoConnectLink,
	countGmailUnreadViaNango,
	createGmailDraftViaNango,
	hasNangoGmailConnection,
	isNangoConfigured,
	listNangoConnections,
	probeNango,
	type NangoConnection,
	type NangoProbe,
} from "./nango/index.js";
export {
	executeLarkMailTriage,
	probeLarkCli,
	type LarkCliProbe,
	type LarkMailTriageInput,
	type LarkMailTriageResult,
} from "./feishu/index.js";
export {
	executeSlackUnread,
	probeSlackCli,
	type SlackCliBackend,
	type SlackCliProbe,
	type SlackUnreadResult,
} from "./slack/index.js";
export {
	isOfficeChannelId,
	normalizeOfficeCliArgs,
	openOfficeSetupInTerminal,
	probeOfficeChannels,
	runOfficeCli,
	type OfficeChannelId,
	type OfficeChannelProbe,
	type OfficeCliResult,
} from "./office/index.js";
export {
	getPluginsDir,
	loadPluginManifests,
	probePlugins,
	runPluginCli,
	type PluginCliResult,
	type PluginManifest,
	type PluginProbe,
} from "./plugins/index.js";
export {
	activateAgentConnectFlow,
	cancelConnectFlow,
	getConnectFlowSession,
	pollConnectFlow,
	resolveConnectTarget,
	startConnectFlow,
	type ConnectFlowKind,
	type ConnectFlowPollResult,
	type ConnectFlowStart,
	type ConnectTarget,
} from "./office/auth-flow.js";
export {
	captureScreenshot,
	calendarBinaryCandidates,
	formatCalendarBrief,
	isCalendarFeatureEnabled,
	listUpcomingCalendarEvents,
	probeCalendarAccess,
	probeScreenCapture,
	readFrontWindowAccessibilityText,
	readProcessAccessibilityText,
	runCalendarBriefSelfCheck,
	type CalendarAccessProbe,
	type CalendarEventBrief,
	type FrontWindowAccessibility,
	type ScreenshotResult,
	type ScreenshotTarget,
	type ScreenCaptureProbe,
} from "./macos/index.js";
export {
	createLocalTaskEmitter,
	parseLocalTaskReturn,
	LOCAL_TASK_RETURN_INSTRUCTIONS,
	type LocalTaskArtifact,
	type LocalTaskEvent,
	type LocalTaskEventCallback,
	type LocalTaskSource,
	type LocalTaskStatus,
	type MemoryCandidate,
} from "./task-events.js";
