import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { resolveDataDir } from "../data-dir.js";
import { loadImportedInputHabits } from "./import.js";
import { parseSogouSgpuBin, sogouReadingToRime } from "./sogou-sgpu.js";
import type { PersonalLexiconEntry } from "./types.js";

const RIME_EXPORT_DIR = join(resolveDataDir(), "rime-export");

export interface RimeExportReport {
	exportedAt: string;
	outDir: string;
	dictLines: number;
	customPhraseLines: number;
	files: string[];
	notes: string[];
}

function ensureOutDir(): string {
	if (!existsSync(RIME_EXPORT_DIR)) mkdirSync(RIME_EXPORT_DIR, { recursive: true });
	return RIME_EXPORT_DIR;
}

function entriesFromSogouBin(binPath: string): Array<{ surface: string; reading: string; freq: number }> {
	return parseSogouSgpuBin(binPath).map((e) => ({
		surface: e.surface,
		reading: e.reading,
		freq: e.freq,
	}));
}

function rimeWeight(freq: number | undefined): number {
	if (!freq || freq < 1) return 1;
	return Math.min(freq, 9999);
}

function writeUserDict(
	outDir: string,
	rows: Array<{ surface: string; reading: string; weight: number }>,
): string {
	const path = join(outDir, "zhigeng.user.dict.yaml");
	const body = rows.map((r) => `${r.surface}\t${r.reading}\t${r.weight}`).join("\n");
	const yaml = `# Rime dictionary — generated by Zhigeng input-habit exporter
# encoding: utf-8
# Deploy: copy to ~/Library/Rime/ and add zhigeng.user to import_tables, then redeploy Squirrel.

---
name: zhigeng.user
version: "1.0"
sort: by_weight
...

${body}
`;
	writeFileSync(path, yaml, "utf8");
	return path;
}

function writeCustomPhrases(outDir: string, phrases: Array<{ shortcut: string; surface: string }>): string | null {
	if (phrases.length === 0) return null;
	const path = join(outDir, "zhigeng.custom.txt");
	const body = phrases.map((p) => `${p.shortcut}\t${p.surface}`).join("\n");
	writeFileSync(path, `# Rime custom phrase — code<TAB>phrase\n${body}\n`, "utf8");
	return path;
}

function writePatchSnippet(outDir: string): string {
	const path = join(outDir, "default.custom.yaml.snippet");
	const snippet = `# Merge into ~/Library/Rime/default.custom.yaml (or rime_ice.custom.yaml)
#
# patch:
#   "engine/translators/@before 0":
#     - punct_translator
#     - script_translator
#     - table_translator@custom_phrase
#   custom_phrase:
#     dictionary: ""
#     user_dict: zhigeng.custom
#     db_class: stabledb
#     enable_completion: false
#     enable_sentence: false
#     initial_quality: 9999
#
# In your main dict yaml (e.g. rime_ice.dict.yaml), add to import_tables:
#   - zhigeng.user
`;
	writeFileSync(path, snippet, "utf8");
	return path;
}

/** ponytail: test exporter — sogou official .bin or existing input-habits.json → Rime files under ~/.zhigeng/rime-export/ */
export function exportInputHabitsToRime(opts?: { sogouBinPath?: string }): RimeExportReport {
	const outDir = ensureOutDir();
	const notes: string[] = [];
	const files: string[] = [];

	let wordRows: Array<{ surface: string; reading: string; weight: number }> = [];
	const phrases: Array<{ shortcut: string; surface: string }> = [];

	if (opts?.sogouBinPath) {
		const raw = entriesFromSogouBin(opts.sogouBinPath);
		notes.push(`搜狗官方备份 SGPU: ${raw.length} 条`);
		for (const e of raw) {
			if (!e.surface.trim()) continue;
			const reading = e.reading ? sogouReadingToRime(e.reading) : "";
			if (!reading) continue;
			wordRows.push({ surface: e.surface, reading, weight: rimeWeight(e.freq) });
		}
	}

	const stored = loadImportedInputHabits();
	if (stored) {
		for (const e of stored.entries) {
			if (e.shortcut && e.surface) {
				phrases.push({ shortcut: e.shortcut, surface: e.surface });
			}
		}
		if (phrases.length > 0) notes.push(`自定义短语（来自 input-habits.json）: ${phrases.length} 条`);
		if (!opts?.sogouBinPath && stored.entries.length > 0) {
			for (const e of stored.entries) {
				if (e.shortcut || !e.reading) continue;
				wordRows.push({
					surface: e.surface,
					reading: sogouReadingToRime(e.reading),
					weight: 1,
				});
			}
			notes.push(`词库（来自 input-habits.json）: ${wordRows.length} 条`);
		}
	}

	// dedupe words
	const seen = new Set<string>();
	wordRows = wordRows.filter((r) => {
		const key = `${r.surface}\t${r.reading}`;
		if (seen.has(key)) return false;
		seen.add(key);
		return true;
	});

	files.push(writeUserDict(outDir, wordRows));
	const customPath = writeCustomPhrases(outDir, phrases);
	if (customPath) files.push(customPath);
	files.push(writePatchSnippet(outDir));

	return {
		exportedAt: new Date().toISOString(),
		outDir,
		dictLines: wordRows.length,
		customPhraseLines: phrases.length,
		files,
		notes,
	};
}

export function defaultRimeExportDir(): string {
	return join(homedir(), ".zhigeng", "rime-export");
}
